### ISSUE TITLE
Connection refused with 1883 and 1884 disabled

### ISSUE THREAD

**Issue by raidnet-ms** [lolouk44/hassio-addons#43]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ x] Xiaomi Mi Scale

**Describe the bug**
Unable to connect if default mqtt port 1883 is disabled

**To Reproduce**
Set the configuration with non default mqtt ports to use SSL encryption.

**Expected behaviour**
Connect to mqtt with SSL on mqtt secure port

**Screenshots**
--- - Starting Xiaomi mi Scale...
---- Loading Config From Add-On Options...
--- - Config Loaded...
Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 270, in <module>
    main()
  File "/opt/miscale/Xiaomi_Scale.py", line 236, in main
    discovery()
  File "/opt/miscale/Xiaomi_Scale.py", line 123, in discovery
    publish.single(
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/publish.py", line 227, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/publish.py", line 163, in multiple
    client.connect(hostname, port, keepalive)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

**Scale (please complete the following information):**
 - Name mi scale
 - Model # 2

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container [e.g. Raspberry Pi, NUC]
 - Bluetooth device used [e.g. Built-in, USB Dongle]
hassio on raspberry pi4 8gb builtin bluetooth
**Additional context**
on default port is working fine

**Comment by lolouk44** [comment]
Thanks. I've just pushed a fix for this.
Let me know if you still have issues after the update

**Comment by lolouk44** [comment]
Not heard back from you, I'll assume it's resolved

**Comment by raidnet-ms** [comment]
sorry, for some reason I did not recive the notification.
It is working, thank you!!
