### ISSUE TITLE
Socket timed out

### ISSUE THREAD

**Issue by odwrotnie** [lolouk44/hassio-addons#61]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [x] Xiaomi Mi Scale

**Describe the bug**
It shows exception in the log after installation and configuration

**To Reproduce**
I have just installed the extension

**Expected behaviour**
It should work ;)

**Screenshots**
This is the log:
```
-------------------------------------
2022-04-18 11:11:50 - Starting Xiaomi mi Scale...
2022-04-18 11:11:50 - Loading Config From Add-On Options...
2022-04-18 11:11:50 - Config Loaded...
Traceback (most recent call last):
  File "/opt/miscale/Xiaomi_Scale.py", line 280, in <module>
    main()
  File "/opt/miscale/Xiaomi_Scale.py", line 246, in main
    discovery()
  File "/opt/miscale/Xiaomi_Scale.py", line 132, in discovery
    publish.single(
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/publish.py", line 227, in single
    multiple([msg], hostname, port, client_id, keepalive, will, auth, tls,
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/publish.py", line 163, in multiple
    client.connect(hostname, port, keepalive)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

**Scale (please complete the following information):**
 - Mi Body Composition Scale
 - Model 2

**Device running Home Assistant (please complete the following information):**
 - Device used to run the Script/Container: Dell Wyse
 - Bluetooth device used [e.g. Built-in, USB Dongle]

**Comment by lolouk44** [comment]
it sounds like you've not configured your  MQTT Broker connection settings correctly.
Go back to the add-on config option and double check your MQTT Settings

**Comment by lolouk44** [comment]
Issue has become stale, closing...
