### ISSUE TITLE
errors on load

### ISSUE THREAD

**Issue by magiva** [lolouk44/hassio-addons#66]
**Select Add-On (place a lowercase `x` for the relevant add-on)**
- [ ] Xiaomi Mi Scale

**Describe the bug**
2022-10-05 17:46:07 - Initialization Completed, Waiting for Scale...
ERROR:root:A message handler raised an exception: 'Icon'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dbus_fast/message_bus.py", line 737, in _process_message
    result = handler(msg)
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/manager.py", line 790, in _parse_msg
    del self_interface[name]
KeyError: 'Icon'
ERROR:root:A message handler raised an exception: 'Icon'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dbus_fast/message_bus.py", line 737, in _process_message
    result = handler(msg)
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/manager.py", line 790, in _parse_msg
    del self_interface[name]
KeyError: 'Icon'

**To Reproduce**
from boot

**Expected behaviour**
no error

note that this seems to be of no significant problem, just shows this error, still gets data from scale

**Scale (please complete the following information):**
Mi Body Composition Scale 2

**Device running Home Assistant (please complete the following information):**
Raspberry Pi with HA running inside of docker
USB Dongle

pi@raspberrypi:~ $ lsusb
Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle ( HCI mode)

**Comment by lolouk44** [comment]
I need more info please.
I've set up a template to try and capture as many details as possible, please provide them

**Comment by magiva** [comment]
info updated

**Comment by lolouk44** [comment]
> note that this seems to be of no significant problem, just shows this error, still gets data from scale

Do I understand correctly that you're getting scale readings in HA but you're also having the error in your original post?
If so I wonder if this is coming from the add-on at all, as it doesn't look related; even though the error message is about bluetooth, it's about an Icon entity which is not related to my code in any way.
I'm in the process of adding more logging anyway so if you give me a couple of days hopefully we can reveal a bit more of what's going on behind the curtains and confirm if related or not.

**Comment by magiva** [comment]
yes correct,  I noticed the error in the log so i tried the scales and data
was posted.
so the error is passive but i thought still worth logging it to you.

**Comment by lolouk44** [comment]
@magiva can you try version 0.3.5 please?
I've added more logging so 
Wanted to see what you get. Be sure to set logging level to DEBUG (see doc)

**Comment by magiva** [comment]
i did and cannot replicate the issue

2022-10-10 16:25:04 - Loading Config From Add-On Options...
2022-10-10 16:25:04 - (INFO) -------------------------------------
2022-10-10 16:25:04 - (INFO) Starting Xiaomi mi Scale v0.3.5...
2022-10-10 16:25:04 - (INFO) Loading Config From Options.json...
2022-10-10 16:25:04 - (INFO) Logging Level Set to DEBUG...
2022-10-10 16:25:04 - (DEBUG) MISCALE_MAC read from config: 5C:CA:D3:CA:28:A9
2022-10-10 16:25:04 - (DEBUG) MQTT_USERNAME read from config: admin
2022-10-10 16:25:04 - (DEBUG) MQTT_PASSWORD read from config: ***
2022-10-10 16:25:04 - (DEBUG) MQTT_HOST read from config: 192.168.86.34
2022-10-10 16:25:04 - (DEBUG) MQTT_RETAIN read from config: True
2022-10-10 16:25:04 - (DEBUG) MQTT_PORT read from config: 1883
2022-10-10 16:25:04 - (DEBUG) MQTT_TLS_CACERTS read from config: Path
to CA Cert File
2022-10-10 16:25:04 - (DEBUG) MQTT_TLS_INSECURE read from config: False
2022-10-10 16:25:04 - (DEBUG) MQTT_PREFIX read from config: miscale
2022-10-10 16:25:04 - (DEBUG) MQTT_DISCOVERY read from config: True
2022-10-10 16:25:04 - (DEBUG) MQTT_DISCOVERY_PREFIX read from config:
homeassistant
2022-10-10 16:25:04 - (DEBUG) HCI_DEV read from config: hci0
2022-10-10 16:25:04 - (DEBUG) BLUEPY_PASSIVE_SCAN read from config: True
2022-10-10 16:25:04 - (INFO) Config Loaded...
2022-10-10 16:25:04 - (INFO) MQTT Discovery Setup Completed...
2022-10-10 16:25:05 - (INFO) -------------------------------------
2022-10-10 16:25:05 - (INFO) Initialization Completed, Waiting for Scale...
2022-10-10 16:25:05 - (DEBUG) Using selector: EpollSelector

**Comment by lolouk44** [comment]
so I take it the add-on is working correctly and that you'll get data displayed if you step on the scale and weigh yourself?
If so, please close this issue 😃

**Comment by magiva** [comment]
yes all good, the issue i see is with bluetooth stopping since the has gods changed it.....
