### ISSUE TITLE
Bug when publishing to mqtt

### ISSUE THREAD

**Issue by cob94440** [lolouk44/hassio-addons#83]
Hello, i've just setup your addon in latest ha version.
Everything seems fine scale is ok but it does'nt publish to mqtt with error :
```
2023-04-17 11:51:39 - (INFO) Publishing data to topic miscale/Chris/weight: {"weight":93.20,"weight_unit":"kg","bmi":29.42,"basal_metabolism":1704.85,"visceral_fat":23.21,"timestamp":"2023-04-17T11:51:39+00:00"}
2023-04-17 11:51:39 - (INFO) Data Published ...
2023-04-17 11:54:56 - (ERROR) A message handler raised an exception: 'Modalias'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dbus_fast/message_bus.py", line 737, in _process_message
    result = handler(msg)
  File "/usr/local/lib/python3.9/site-packages/bleak/backends/bluezdbus/manager.py", line 790, in _parse_msg
    del self_interface[name]
KeyError: 'Modalias'

```

**Comment by lolouk44** [comment]
Sorry I was on holidays. Can you please fill in all the requested info order to help me assist you?
Also set DEBEUG_LEVEL to DEBUG and post your logs here
